[package]
name = "smithay-clipboard"
version = "0.8.0"
authors = [
    "Kirill Chibisov <contact@kchibisov.com>",
    "Victor Berger <victor.berger@m4x.org>",
]
edition = "2021"
description = "Provides access to the wayland clipboard for client applications."
repository = "https://github.com/smithay/smithay-clipboard"
documentation = "https://smithay.github.io/smithay-clipboard"
license = "MIT"
keywords = ["clipboard", "wayland"]
rust-version = "1.65.0"

[dependencies]
libc = "0.2.149"
sctk = { package = "smithay-client-toolkit", version = "0.20", default-features = false, features = [
    "calloop",
] }
wayland-backend = { version = "0.3.3", default_features = false, features = [
    "client_system",
] }
raw-window-handle = { version = "0.6", optional = true }

[dev-dependencies]
dirs = "5.0.1"
sctk = { package = "smithay-client-toolkit", version = "0.20", default-features = false, features = [
    "calloop",
    "xkbcommon",
] }
thiserror = "1.0.57"
url = "2.5.0"

[features]
default = ["dlopen", "dnd", "rwh-6"]
rwh-6 = ["raw-window-handle"]
dnd = []
dlopen = ["wayland-backend/dlopen"]

[patch.crates-io]
wayland-sys = { git = "https://github.com/smithay/wayland-rs" }
wayland-backend = { git = "https://github.com/smithay/wayland-rs" }
wayland-server = { git = "https://github.com/smithay/wayland-rs" }
wayland-scanner = { git = "https://github.com/smithay/wayland-rs" }
wayland-client = { git = "https://github.com/smithay/wayland-rs" }
wayland-protocols = { git = "https://github.com/smithay/wayland-rs" }
wayland-protocols-wlr = { git = "https://github.com/smithay/wayland-rs" }
wayland-cursor = { git = "https://github.com/smithay/wayland-rs" }
smithay-client-toolkit = { git = "https://github.com/ids1024/client-toolkit", branch = "wayland-update" }
